import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Near Glasses",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen">
      <Navbar />
      
      <div className="mx-auto max-w-3xl px-6 py-24 sm:py-32">
        <h1 className="mb-4 font-sans text-4xl font-medium tracking-tight sm:text-5xl">
          Privacy <span className="font-pixel">Policy</span>
        </h1>
        <p className="mb-12 font-mono text-sm tracking-[0.1em] text-foreground/50">
          Last Updated: July 29, 2026
        </p>

        <div className="space-y-10 font-sans text-base leading-relaxed tracking-tight opacity-80 sm:text-lg">
          
          <section>
            <p className="font-medium text-foreground opacity-100">
              At Near, we believe privacy is a fundamental human right. Our application is designed to help you reclaim your privacy from intrusive smart glasses and recording devices. Because our core mission is privacy, we have built the app to be completely private by design.
            </p>
          </section>

          <section>
            <h2 className="mb-4 font-sans text-2xl font-medium text-foreground opacity-100">
              1. Data Collection
            </h2>
            <p>
              Near is designed to operate with minimal data collection. However, to ensure the stability and improvement of the App, the following data may be collected but is <strong>not linked to your identity</strong>:
            </p>
            <ul className="list-inside list-disc mt-4 space-y-2">
              <li><strong>Diagnostics:</strong> Crash logs and performance data to help us identify and fix bugs.</li>
              <li><strong>Identifiers:</strong> Anonymous device identifiers used strictly for diagnostic grouping and analytics.</li>
            </ul>
            <p className="mt-4">
              We do not collect, store, transmit, or monetize any personally identifiable information (PII). All core detection features operate locally on your device.
            </p>
          </section>

          <section>
            <h2 className="mb-4 font-sans text-2xl font-medium text-foreground opacity-100">
              2. How We Use Bluetooth
            </h2>
            <p>
              The application requires Bluetooth Low Energy (BLE) permissions to function. 
            </p>
            <ul className="list-inside list-disc mt-4 space-y-2">
              <li><strong>Passive Scanning:</strong> Near only listens passively to public advertisement packets broadcasted by devices in your vicinity.</li>
              <li><strong>No Connections:</strong> We never attempt to pair, connect, or communicate with the smart devices detected.</li>
              <li><strong>Local Matching:</strong> Bluetooth MAC addresses and Manufacturer Specific Data are matched against our on-device database of known smart glasses signatures. This data never leaves your phone.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-4 font-sans text-2xl font-medium text-foreground opacity-100">
              3. Why We Need Location Permissions
            </h2>
            <p>
              Apple&apos;s iOS architecture requires Location Services permissions to allow apps to scan for Bluetooth devices in the background over extended periods. We use &quot;Always&quot; location authorization for two strict purposes:
            </p>
            <ul className="list-inside list-disc mt-4 space-y-2">
              <li><strong>Background Scanning:</strong> To keep the app active so it can alert you of threats even when your phone is in your pocket.</li>
              <li><strong>Safe Zones:</strong> To allow you to define geographic safe zones (like your home) where scanning automatically pauses to save battery. The geofencing logic operates strictly on-device. Your GPS coordinates are never recorded, tracked, or sent to us.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-4 font-sans text-2xl font-medium text-foreground opacity-100">
              4. Data Storage and Deletion
            </h2>
            <p>
              Any data generated by the app, such as your history of detected devices, saved &quot;Starred&quot; devices, and custom Safe Zones, is stored securely on your device using local iOS storage (SwiftData/CoreData). 
            </p>
            <p className="mt-4">
              You maintain total control over your data. You can clear your scan history or delete the app at any time, which permanently removes all associated data from your device.
            </p>
          </section>

          <section>
            <h2 className="mb-4 font-sans text-2xl font-medium text-foreground opacity-100">
              5. Local Push Notifications
            </h2>
            <p>
              When a smart glass device is detected nearby, the app triggers a local push notification. Unlike standard push notifications, these do not pass through Apple Push Notification service (APNs) servers or our servers—they are generated locally by your phone&apos;s operating system.
            </p>
          </section>

          <section>
            <h2 className="mb-4 font-sans text-2xl font-medium text-foreground opacity-100">
              6. Changes to This Policy
            </h2>
            <p>
              If we update this Privacy Policy to reflect changes in iOS permissions or new app features, we will update the &quot;Last Updated&quot; date at the top of this page. Because we do not collect your contact information, we cannot email you about changes, so we encourage you to review this page periodically.
            </p>
          </section>

          <section>
            <h2 className="mb-4 font-sans text-2xl font-medium text-foreground opacity-100">
              7. Contact Us
            </h2>
            <p>
              If you have any questions, concerns, or feedback regarding this Privacy Policy, please contact us at <a href="mailto:hello@nearglasses.com" className="text-[#FF2B00] hover:underline">hello@nearglasses.com</a>.
            </p>
          </section>
        </div>
      </div>

      <Footer />
    </main>
  );
}
